# Generated by Django 4.2.3 on 2023-08-14 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisment',
            table='advs',
        ),
    ]
